### ISSUE TITLE
Debian12运行 install --go 报错

### ISSUE THREAD

**Issue by chika0801** [chise0713/sing-box-install#14]
全新DD的Debian12开始。

使用命令：
` bash -c "$(curl -L sing-box.vercel.app)" @ install --go`

首次安装报错信息
```
INFO: No GO found in your machine.
INFO: Upstream GO version = 1.21.5
INFO: Installing GO
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    231      0 --:--:-- --:--:-- --:--:--   232
100 63.5M  100 63.5M    0     0  63.8M      0 --:--:-- --:--:-- --:--:--  108M
go version go1.21.5 linux/amd64
INFO: go installed PATH: /usr/sbin/go (soft symbolic link) PATH: /usr/lib/go/bin/go
INFO: Current compile "releaseTag / branch" is main-next
Using offcial default Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api.
environment: line 239: cd: /root/.cache: No such file or directory
ERROR: Failed to clone repository, check your permission.
```

第2次运行报错信息
```
root@localhost:~# bash -c "$(curl -L sing-box.vercel.app)" @ install --go
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 26886  100 26886    0     0  48160      0 --:--:-- --:--:-- --:--:-- 48160
build-essential	 Version=12.9 ARCH=amd64
INFO: GO Found, PATH=/usr/sbin/go
INFO: Current compile "releaseTag / branch" is main-next
Using offcial default Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api.
environment: line 239: cd: /root/.cache: No such file or directory
ERROR: Failed to clone repository, check your permission.
environment: line 555: sing-box: command not found
Installed: "/usr/share/bash-completion/completions/sing-box"
environment: line 565: sing-box: command not found
Installed: "/usr/share/fish/vendor_completions.d/sing-box.fish"
environment: line 575: sing-box: command not found
Installed: "/usr/share/zsh/site-functions/_sing-box"

```

Debian10运行正常。

**Comment by chise0713** [comment]
- 4f41e87b8e45da359e8ac2427de6a3a325fbdabf

现在应该没问题了

**Comment by chise0713** [comment]
- 9118d7f8551ceb3f9334eb8a05a393fea2add04e

这个是无特权编译的修复

**Comment by chika0801** [comment]
刚测试失败了。新安装的DD12，首次运行  `bash -c "$(curl -L sing-box.vercel.app)" @ install --go`

root@localhost:~#  bash -c "$(curl -L sing-box.vercel.app)" @ install --go
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 27012  100 27012    0     0  42984      0 --:--:-- --:--:-- --:--:-- 42984
useradd: Warning: missing or non-executable shell '/bin/nologin'
Creating group 'sing-box' with GID 1000.
Creating user 'sing-box' (sing-box service) with UID 1000 and GID 1000.
Installed: "/usr/local/etc/sing-box/"
Installed: "/usr/local/etc/sing-box/config.json"
Installed: "/var/lib/sing-box/"
Installed: "/etc/systemd/system/sing-box.service"
Installed: "/etc/systemd/system/sing-box.service.d/"
Installed: "/etc/systemd/system/sing-box.service.d/10-donot_touch.conf"
Installed: "/etc/systemd/system/sing-box@.service"
Installed: "/etc/systemd/system/sing-box@.service.d/"
Installed: "/etc/systemd/system/sing-box@.service.d/10-donot_touch.conf"
######################################################################## 100.0%
INFO: No GO found in your machine.
INFO: Upstream GO version = 1.21.5
INFO: Installing GO
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    229      0 --:--:-- --:--:-- --:--:--   229
100 63.5M  100 63.5M    0     0  59.7M      0  0:00:01  0:00:01 --:--:--  104M
go version go1.21.5 linux/amd64
INFO: go installed PATH: /usr/bin/go (soft symbolic link) PATH: /usr/lib/go/bin/go
INFO: Current compile "releaseTag / branch" is main-next
Using offcial default Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api.
environment: line 238: git: command not found
ERROR: Failed to clone repository, check your permission.
root@localhost:~# 

手动安装 apt install git后，正常。你少一个git检查？

**Comment by chika0801** [comment]
`bash -c "$(curl -L sing-box.vercel.app)" @ compile
`

用这命令能在当前目录下创建sing-box文件

**Comment by chise0713** [comment]
> `bash -c "$(curl -L sing-box.vercel.app)" @ compile
> `
> 
> 用这命令能在当前目录下创建sing-box文件

这个是编译一份sing-box到$HOME

**Comment by chise0713** [comment]
现在的问题是缺少是否安装了git的检测。
