### ISSUE TITLE
获取sing-box源代码关键部分缺失

### ISSUE THREAD

**Issue by PaPerseller** [chise0713/sing-box-install#15]
debian12
使用 `bash -c "$(curl -L sing-box.vercel.app)" @ install` 出现报错 `ERROR: Failed to Install "/usr/local/bin/sing-box"` 转而使用编译命令 `bash -c "$(curl -L sing-box.vercel.app)" @ compile` 或 `bash -c "$(curl -L sing-box.vercel.app)" @ install --go`，报错 `ERROR: Failed to cd /root/.cache/sing-box` 
手动在 /root/.cache/ 中 git clone sing-box 源代码，再次执行才进入编译安装流程

**Comment by chise0713** [comment]
请使用 `bash -x` 执行脚本，并将输出内容粘贴到网络剪切板，或者直接上传输出内容为文件。

**Comment by chise0713** [comment]
我成功复现了，修复很快就会放出

**Comment by chise0713** [comment]
Fixed
