### ISSUE TITLE
亲，能不能支持下alpine系统，这个省内存，现在小鸡用的多，谢谢

### ISSUE THREAD

**Issue by sos801107** [chise0713/sing-box-install#16]
亲，能不能支持下alpine系统，这个省内存，现在小鸡用的多，谢谢

**Comment by chise0713** [comment]
alpine 默认安装没有 systemd，安装 systemd 之后反而没有优势，我个人认为没必要加。

**Comment by chise0713** [comment]
No response after 2 weeks, closing.
